<?php

/** @var \AHT\Crud\Block\Template $crud */
?>
<head>
    <title>Crud Practice - Insert</title>
</head>

<div class="template">
    <div class="container">
        <form method='POST' action="save">
            <div class="form-group">
                <label for="title"><b>Title</b></label>
                <input type="text" class="form-control" id="title" placeholder="Title" name="title">
            </div>
            <br>
            <div class="form-group">
                <label for="detail"><b>Detail</b></label>
                <input type="text" class="form-control" id="detail" placeholder="Detail" name="detail">
            </div>
            <br>
            <button type="submit" class="btn btn-primary" name="btn_create">Submit</button>
        </form>
    </div>

</div>
